### PR TITLE
fix(constants): update docs links

### PR DESCRIPTION
**Pull request by ashutoshvarma**
Fix links in `constants/docLinks.ts` which were broken

### CODE REVIEW

**Comment by ashutoshvarma** [comment]
Looks like I should have modified `/utils/getDocLinks.ts` in develop branch instead of master 🤔. 
Should I create PR for develop and close this one?

**Comment by daywiss** [comment]
Thanks for your PR!  I think its fine how you have it. This flew under radar since noone was tagged for review. Will look over and get back to you

**Comment by daywiss** [comment]
@ashutoshvarma click the details link next to dco, it should take you [here](https://github.com/UMAprotocol/emp-tools/pull/210/checks?check_run_id=2016497188)  and follow the directions for signing off on the commit.

**Comment by ashutoshvarma** [comment]
@daywiss I signed off the commit. Do I have to sign this commit with my PGP key also?

**Comment by daywiss** [comment]
> @daywiss I signed off the commit. Do I have to sign this commit with my PGP key also?

No i think you are good

**Comment by pemulis** [comment]
@daywiss do you think this is ready to deploy? Looks like we just need authorization on Vercel.

**Comment by daywiss** [comment]
@pemulis going to check in with @nicholaspai but yea i think it looks good to go

**Review by nicholaspai — APPROVED** [review]
URL's check out, LGTM

**Pull request merged**
